# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(802, 610)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 30, 651, 441))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 185, 47))
        self.label_2.setStyleSheet("font: 28pt \"微軟正黑體\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 170, 185, 42))
        self.pushButton_4.setStyleSheet("\n"
"QPushButton {\n"
"background-color: rgb(220, 220, 220);\n"
"border-radius: 10px;\n"
"border: 2px solid #999999;\n"
"padding: 6px 12px;\n"
"font: 20pt \"微軟正黑體\";\n"
"}\n"
"\n"
"QPushButton:hover  {\n"
"background-color: #8f8f8f;\n"
"border-color: #5b5b5b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #5e5e5e;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 191, 61))
        self.label.setStyleSheet("font: 28pt \"微軟正黑體\";")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 100, 185, 42))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton {\n"
"background-color: rgb(220, 220, 220);\n"
"border-radius: 10px;\n"
"border: 2px solid #999999;\n"
"padding: 6px 12px;\n"
"font: 20pt \"微軟正黑體\";\n"
"}\n"
"\n"
"QPushButton:hover  {\n"
"background-color: #8f8f8f;\n"
"border-color: #5b5b5b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #5e5e5e;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 691, 61))
        self.label_3.setStyleSheet("font: 28pt \"微軟正黑體\";\n"
"color: rgb(255, 14, 14);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 100, 191, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "猜數字遊戲"))
        self.pushButton_4.setText(_translate("Dialog", "遊戲開始"))
        self.label.setText(_translate("Dialog", "猜數字遊戲"))
        self.pushButton_3.setText(_translate("Dialog", "確定"))
        self.label_3.setText(_translate("Dialog", "請輸入1~100之中的數字"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
